# Generated by Django 5.0.9 on 2024-10-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='Subscription',
            new_name='subscription',
        ),
    ]
