# Generated by Django 5.0.9 on 2024-10-24 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('enterprise', 'Enterprise Perm'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm'), ('basic_ai', 'Basic AI Perm')]},
        ),
        migrations.AddField(
            model_name='subscription',
            name='featured',
            field=models.BooleanField(default=True, help_text='Featured on the pricing page'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.IntegerField(default=-1, help_text='Order sequence on the pricing page'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
